### ISSUE TITLE
Creating a in-browser playground for Closh

### ISSUE THREAD

**Issue by bigDaddyS1oth** [dundalek/closh#29]
Hello, 

While I'm not nearly as experienced as probably most of you all who look into Closh are, I thought it might be interesting if we could create sort of a in-browser Closh playground for people to check out easily. Obviously it'd be written in Clojure[Script] 😉, but I think it'd be a fun project.

**Comment by dundalek** [comment]
I think it would be doable. Bootstrapped ClojureScript in browser has been done and there are javascript libraries available for tty rendering.

The power of Closh is about combining unix commands, otherwise you just have a simple cljs repl. So the trickiest part would be to either implement mocks of some unix commands or run it on the server and figure out some sandboxing so that server does not get pwned.

I will keep this open in case someone is looking for an inspiration on what to hack on.

**Comment by dundalek** [comment]
I just discovered [fish playground](https://rootnroll.com/d/fish-shell/) and contacted [Root&Roll](http://welcome.rootnroll.com/) folks to see if it would be possible to create a playground for closh too.

**Comment by dundalek** [comment]
Created a closh playground: https://repl.it/@dundalek/closh-playground
